minimum_pre_commit_version: "4.6.0"

repos:
  - repo: local
    hooks:
      - id: ruff-format-check
        name: Ruff format check
        entry: make py-format-check
        language: system
        pass_filenames: false

      - id: ruff-lint
        name: Ruff lint
        entry: make py-lint
        language: system
        pass_filenames: false

      - id: ty-check
        name: ty type check
        entry: make py-type
        language: system
        pass_filenames: false

      - id: verible-format-check
        name: Verible format check
        entry: make sv-format-check
        language: system
        pass_filenames: false

      - id: verible-lint
        name: Verible lint
        entry: make sv-lint
        language: system
        pass_filenames: false

      - id: verilator-lint
        name: Verilator lint-only
        entry: make verilator-lint
        language: system
        pass_filenames: false
