# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"
hooks = [
  {
    id = "ruff-format-check",
    name = "Ruff format check",
    entry = "make py-format-check",
    language = "system",
    pass_filenames = false,
    priority = 0
  },
  {
    id = "ruff-lint",
    name = "Ruff lint",
    entry = "make py-lint",
    language = "system",
    pass_filenames = false,
    priority = 0
  },
  {
    id = "ty-check",
    name = "ty type check",
    entry = "make py-type",
    language = "system",
    pass_filenames = false,
    priority = 0
  },
  {
    id = "markdown-lint",
    name = "Markdown lint",
    entry = "make md-lint",
    language = "system",
    pass_filenames = false,
    priority = 0
  },
  {
    id = "verible-format-check",
    name = "Verible format check",
    entry = "make sv-format-check",
    language = "system",
    pass_filenames = false,
    priority = 0
  },
  {
    id = "verible-lint",
    name = "Verible lint",
    entry = "make sv-lint",
    language = "system",
    pass_filenames = false,
    priority = 0
  },
  {
    id = "verilator-lint",
    name = "Verilator lint-only",
    entry = "make verilator-lint",
    language = "system",
    pass_filenames = false,
    priority = 0
  }
]
